### ISSUE TITLE
Development Roadmap

### ISSUE THREAD

**Issue by brunohgv** [brunohgv/course-catcher#1]
# Development Roadmap

------

- [ ] Get Udemy link from telegram chat
    - [ ] Detect a message event in telegram
    - [ ] Get message body

------

- [ ] "Buy" a course
    - [ ] Access udemy page using webdriver
    - [ ] Check if the course is realy free
    - [ ] Click "buy" button

------

- [ ] Handle different cases
    - [ ] Login if not logged in
    - [ ] Abort if the course is not free
